language: go

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile go-plurk-robot.cov github.com/elct9620/go-plurk-robot/plurk
  - $HOME/gopath/bin/goveralls -coverprofile=go-plurk-robot.cov -service=travis-ci
