language: go

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile=go-plurk-robot.cov -service=travis-ci
